id = "cyberpunk-2077-theme"
name = "Cyberpunk 2077"
version = "0.0.3"
schema_version = 1
authors = ["Thomas Simmer"]
description = "Inspired by Cyberpunk 2077 (Arasaka, Biotechnica, Softsys, NCPD, Kang Tao, Militech, Delamain, Pink neon, Mox)"
repository = "https://github.com/thomassimmer/cyberpunk-2077-zed-extension"